workmanager:
  auth:
    jwt-secret: "f623c7a6-e658-4566-bbee-ecc070321553"
    jwt-expiration-ms: 86400000
  storage:
    root-directory:
      "D:\\storage"
    qa-table-template-location:
      "D:\\storage\\qatemplate.docx"
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  datasource:
    url: "jdbc:${WORK_DB_TYPE:mysql}://${WORK_DB_URL:localhost}:${WORK_DB_PORT:3306}/work_management?serverTimezone=UTC"
    username: ${WORK_DB_USERNAME:root}
    password: ${WORK_DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
server:
  port: 8090
logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.springframework.security: INFO
    com.my.workmanagement: DEBUG
springfox:
  documentation:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
aliyun:
  endpoint: "oss-cn-shanghai.aliyuncs.com"
  accessKeyId: "${OSS_KEY}"
  accessKeySecret: "${OSS_SECRET}"
  bucketName: "work-management"
